name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  build-test-and-push:
    runs-on: ubuntu-20.04

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # Step 4: Run tests
    - name: Run pytest
      run: |
        pytest tests/
    
    # Step 5: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 6: Build the Docker image
    - name: Build Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/my-app"
        TAG="${{ github.sha }}"
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .

    # Step 7: Push the Docker image
    - name: Push Docker image
      run: |
        IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/my-app"
        TAG="${{ github.sha }}"
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$TAG

